name: vislex

services:
  vislex:
    image: "docker.io/shaundcn/vislex:${VISLEX_TAG:-latest}"
    container_name: vislex
    init: true
    ports:
      - "${HOST_PORT:-8080}:8000"
    environment:
      TRUSTED_HOSTS: "*"
    volumes:
      - "${VISLEX_INPUT_DIR:-./input}:/app/input"
      - "${VISLEX_OUTPUT_DIR:-./output}:/app/output"
      - "${VISLEX_DATA_DIR:-./data}:/app/data"
